name: Latest blog posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Pull in tanducmai.com posts
        uses: gautamkrishnar/blog-post-workflow@1.8.4
        with:
          feed_list: "https://tanducmai.com/blog/index.xml"
          template: "$newline $emojiKey(💯,🔥,💫,🚀,🌮) $date - [$title]($url)"
          date_format: "UTC:mmmm d, yyyy"
          commit_message: "Update with the latest blog posts"
          remove_duplicates: true
