name: Latest blog posts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12,21 * * *"
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Pull in tanducmai.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://tanducmai.com/posts/index.xml"
          template: "$newline - $emojiKey(💯,🔥,💫,🚀,🌮) $date - [$title]($url)"
          date_format: "UTC:mmmm d, yyyy"
          commit_message: "Update README with the latest blog posts"
          remove_duplicates: true
