name: 📚 Update latest blogs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Pull in tanducmai.com blogs
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://tanducmai.com/posts/index.xml"
          template: "$newline - $emojiKey(💯,🔥,💫,🚀,🌮) $date - [$title]($url)"
          date_format: "UTC:mmmm d, yyyy"
          commit_message: "Update README with the latest blog posts"
          remove_duplicates: true
