name: Update StackOverflow activities

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Pull in @tanducmai StackOverflow activities
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://stackoverflow.com/feeds/user/16999206"
          template: "<tr><td>$title</td><td>$url</td></tr>"
          commit_message: "Update with the latest StackOverflow activities"
