name: 💻 Update StackOverflow activities

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
        
      - name: ⤵️ Pull in @tanducmai Activities
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://stackoverflow.com/feeds/user/16999206"
          template: "<tr><td>$title</td><td>$url</td></tr>"
          commit_message: "docs(readme): update StackOverflow activities"
