name: Waka Readme

on:
  schedule:
    - cron: '15 */12 * * *' # at 00:15 and 12:15 UTC every day
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
