name: Waka coding activities

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
